/**
 * AUTO-GENERATED by scripts/stamp-version.js — do not hand-edit.
 * Regenerated on every commit via .husky/pre-commit, AND on npm start
 * so what the badge says is always what is being served (#1002).
 *
 * builtAt only moves when something else does (#1071) — otherwise re-running
 * this would dirty the working tree for no reason.
 */
export const VERSION = {
  "version": "4.0.6",
  "commit": "672a6787",
  "builtAt": "2026-09-29T04:24:19.832Z",
  "branch": "claude/fervent-noether-ydmxea",
  "dirty": true,
  "ahead": 1,
  "behind": 0,
  "upstream": "origin/claude/fervent-noether-ydmxea"
};
