/**
 * AUTO-GENERATED by scripts/stamp-version.js — do not hand-edit.
 * Regenerated on every commit via .husky/pre-commit.
 */
export const VERSION = {
  "version": "3.0.91",
  "commit": "db72267d",
  "builtAt": "2026-08-21T23:32:02.395Z"
};
