/**
 * AUTO-GENERATED by scripts/stamp-version.js — do not hand-edit.
 * Regenerated on every commit via .husky/pre-commit.
 */
export const VERSION = {
  "version": "3.0.10",
  "commit": "4e594f1",
  "builtAt": "2026-08-09T21:55:04.794Z"
};
