import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

/**
 * COMPLIANCE GATE (#230): the A.I. Docs page lists every docs/claude/ doc, in
 * reading order, reachable from a home/nav menu item.
 *
 * pages/ai-docs.html is generated by scripts/generate-ai-docs-list.mjs. This gate
 * fails on drift (a docs/claude/*.md not listed, a stale link, a non-root-relative
 * link that 404s under /wb-starter/), on a broken reading order, or if the nav
 * entry is missing. Regenerate: node scripts/generate-ai-docs-list.mjs
 */
const ROOT = process.cwd();
const DIR = path.join(ROOT, 'docs', 'claude');
const PAGE = path.join(ROOT, 'pages', 'ai-docs.html');

const READING_ORDER = ['README.md', 'TIER1-LAWS.md', 'TIER2-DOMAIN-GUIDES.md', 'TIER3-REFERENCE.md'];

function expectedDocs(): string[] {
  return fs.readdirSync(DIR).filter((n) => n.endsWith('.md'));
}
function listed(): { names: string[]; hrefs: string[] } {
  const html = fs.readFileSync(PAGE, 'utf8');
  const names: string[] = [];
  const hrefs: string[] = [];
  for (const m of html.matchAll(/href="([^"]*doc-viewer\.html\?file=docs\/claude\/([^"&]+))"/gi)) {
    hrefs.push(m[1]);
    names.push(m[2]);
  }
  return { names, hrefs };
}

test.describe('A.I. Docs page lists all AI docs, in order, in the menu (#230)', () => {
  const { names, hrefs } = listed();
  const expected = expectedDocs();

  test('lists every docs/claude/*.md (no missing)', () => {
    const missing = expected.filter((d) => !names.includes(d));
    expect(missing, `AI docs not listed (run: node scripts/generate-ai-docs-list.mjs):\n  ${missing.join('\n  ')}`).toEqual([]);
  });

  test('no stale links (every listed doc exists)', () => {
    const stale = names.filter((n) => !fs.existsSync(path.join(DIR, n)));
    expect(stale, `AI Docs page links to non-existent docs:\n  ${stale.join('\n  ')}`).toEqual([]);
  });

  test('links are root-relative (no ../ or leading /)', () => {
    const bad = hrefs.filter((h) => h.startsWith('/') || h.startsWith('../'));
    expect(bad, `AI Docs links must be root-relative:\n  ${bad.join('\n  ')}`).toEqual([]);
  });

  test('tier docs appear in reading order', () => {
    const positions = READING_ORDER.filter((n) => names.includes(n)).map((n) => names.indexOf(n));
    const sorted = [...positions].sort((a, b) => a - b);
    expect(positions, 'tier docs are out of reading order (README → TIER1 → TIER2 → TIER3)').toEqual(sorted);
  });

  // #1083 — John: "remove the demos navigator item as well as the A.I. Docs".
  //
  // The assertion that used to live here required a navigationMenu entry with
  // pageToLoad "ai-docs". That is now the opposite of the requirement, so it is
  // retired rather than inverted: "the nav must NOT offer this" would fail the
  // day someone legitimately puts it back, and this gate is about the PAGE, not
  // about the menu.
  //
  // What replaces it is narrower and still true: the page has to keep working
  // for anyone who reaches it directly at ?page=ai-docs, which is the whole
  // reason the page was kept when the menu item went.
  test('the A.I. Docs page still exists for anyone who visits it directly', () => {
    expect(
      fs.existsSync(path.join(ROOT, 'pages', 'ai-docs.html')),
      'pages/ai-docs.html was removed from the nav (#1083), not from the site — '
        + '?page=ai-docs must still resolve',
    ).toBe(true);
  });
});
