import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

/**
 * COMPLIANCE GATE (#230): the A.I. Docs page lists every docs/claude/ doc, in
 * reading order, reachable from a home/nav menu item.
 *
 * pages/ai-docs.html is generated by scripts/generate-ai-docs-list.mjs. This gate
 * fails on drift (a docs/claude/*.md not listed, a stale link, a non-root-relative
 * link that 404s under /wb-starter/), on a broken reading order, or if the nav
 * entry is missing. Regenerate: node scripts/generate-ai-docs-list.mjs
 */
const ROOT = process.cwd();
const DIR = path.join(ROOT, 'docs', 'claude');
const PAGE = path.join(ROOT, 'pages', 'ai-docs.html');

const READING_ORDER = ['README.md', 'TIER1-LAWS.md', 'TIER2-DOMAIN-GUIDES.md', 'TIER3-REFERENCE.md'];

function expectedDocs(): string[] {
  return fs.readdirSync(DIR).filter((n) => n.endsWith('.md'));
}
function listed(): { names: string[]; hrefs: string[] } {
  const html = fs.readFileSync(PAGE, 'utf8');
  const names: string[] = [];
  const hrefs: string[] = [];
  for (const m of html.matchAll(/href="([^"]*doc-viewer\.html\?file=docs\/claude\/([^"&]+))"/gi)) {
    hrefs.push(m[1]);
    names.push(m[2]);
  }
  return { names, hrefs };
}

test.describe('A.I. Docs page lists all AI docs, in order, in the menu (#230)', () => {
  const { names, hrefs } = listed();
  const expected = expectedDocs();

  test('lists every docs/claude/*.md (no missing)', () => {
    const missing = expected.filter((d) => !names.includes(d));
    expect(missing, `AI docs not listed (run: node scripts/generate-ai-docs-list.mjs):\n  ${missing.join('\n  ')}`).toEqual([]);
  });

  test('no stale links (every listed doc exists)', () => {
    const stale = names.filter((n) => !fs.existsSync(path.join(DIR, n)));
    expect(stale, `AI Docs page links to non-existent docs:\n  ${stale.join('\n  ')}`).toEqual([]);
  });

  test('links are root-relative (no ../ or leading /)', () => {
    const bad = hrefs.filter((h) => h.startsWith('/') || h.startsWith('../'));
    expect(bad, `AI Docs links must be root-relative:\n  ${bad.join('\n  ')}`).toEqual([]);
  });

  test('tier docs appear in reading order', () => {
    const positions = READING_ORDER.filter((n) => names.includes(n)).map((n) => names.indexOf(n));
    const sorted = [...positions].sort((a, b) => a - b);
    expect(positions, 'tier docs are out of reading order (README → TIER1 → TIER2 → TIER3)').toEqual(sorted);
  });

  test('a nav menu item links to the A.I. Docs page', () => {
    const site = JSON.parse(fs.readFileSync(path.join(ROOT, 'config', 'site.json'), 'utf8'));
    const item = (site.navigationMenu || []).find((m: any) => m.pageToLoad === 'ai-docs');
    expect(item, 'config/site.json navigationMenu has no A.I. Docs entry (pageToLoad: "ai-docs")').toBeTruthy();
  });
});
