import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

/**
 * #237: the bare /demos/ directory URL served nothing useful (a directory
 * listing or 404, depending on host) — you had to go through the SPA's
 * ?page=demos route. Added demos/index.html: a plain, standalone page (no
 * SPA, no WB runtime import) generated by scripts/generate-demos-list.mjs
 * alongside pages/demos.html, so it works even independent of the app.
 * Static file servers (this project's express server, GitHub Pages) serve
 * index.html for a directory request by default.
 */
test.describe('demos/index.html (#237)', () => {
  test('is up to date with the demos/ folder (run generate-demos-list.mjs if this fails)', () => {
    const demosDir = path.join(process.cwd(), 'demos');
    const SKIP = /(^|[-.])(debug|test|test-harness|harness|check|scratch)([-.]|$)/i;
    const files = fs.readdirSync(demosDir)
      .filter((n) => n.endsWith('.html') && n !== 'index.html' && !SKIP.test(n.replace(/\.html$/i, '')));
    const indexHtml = fs.readFileSync(path.join(demosDir, 'index.html'), 'utf8');
    for (const f of files) {
      expect(indexHtml, `demos/index.html should link to ${f}`).toContain(`./${f}`);
    }
  });

  test('the bare /demos/ URL serves a real index with working links, no SPA/WB dependency', async ({ page }) => {
    await page.goto('/demos/', { waitUntil: 'domcontentloaded' });
    await expect(page).toHaveTitle(/Demos Index/);
    // #268 consolidated the ~35 single-demo links this used to check for
    // into 8 real category pages (demos/site/*.html) plus the handful of
    // genuinely standalone narrative/tool pages — "more links" was the
    // exact anti-pattern #268 exists to undo. Check for links into every
    // category page instead of a link-count floor.
    const categoryLinks = page.locator('a[href^="./site/"]');
    await expect.poll(() => categoryLinks.count()).toBeGreaterThanOrEqual(8);
    const linkCount = await page.locator('ul a').count();
    expect(linkCount).toBeGreaterThan(0);
    // No framework script — this page must render before/without WB loading.
    const hasWbImport = await page.evaluate(() => !!document.querySelector('script[src*="wb-lazy"], script[src*="core/wb.js"], script[type="module"]'));
    expect(hasWbImport).toBe(false);
  });
});
