import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

/**
 * COMPLIANCE GATE (#229): the Demos page lists EVERY demo in demos/.
 *
 * pages/demos.html is generated by scripts/generate-demos-list.mjs. This gate
 * fails if the page drifts from the folder — a demo added to demos/ but not
 * regenerated, a listed demo whose file was removed, or a link that isn't
 * root-relative (which 404s under the /wb-starter/ base). Regenerate with:
 *   node scripts/generate-demos-list.mjs
 */
const ROOT = process.cwd();
const DEMOS_DIR = path.join(ROOT, 'demos');
const PAGE = path.join(ROOT, 'pages', 'demos.html');

// Must match scripts/generate-demos-list.mjs — internal harnesses aren't listed.
const SKIP = /(^|[-.])(debug|test|test-harness|harness|check|scratch)([-.]|$)/i;

function expectedDemos(): string[] {
  return fs.readdirSync(DEMOS_DIR)
    .filter((n) => n.endsWith('.html') && !SKIP.test(n.replace(/\.html$/i, '')))
    .sort();
}

function listedDemos(): { hrefs: string[]; absolute: string[] } {
  const html = fs.readFileSync(PAGE, 'utf8');
  const hrefs: string[] = [];
  const absolute: string[] = [];
  for (const m of html.matchAll(/href="([^"]*demos\/[^"]+\.html)"/gi)) {
    const h = m[1];
    if (h.startsWith('/') || h.startsWith('../')) absolute.push(h);
    hrefs.push(h.replace(/^.*?demos\//, '')); // basename under demos/
  }
  return { hrefs, absolute };
}

test.describe('Demos page lists every demo (#229)', () => {
  const { hrefs, absolute } = listedDemos();
  const expected = expectedDemos();
  const listedSet = new Set(hrefs);

  test('lists every demos/*.html (no missing)', () => {
    const missing = expected.filter((d) => !listedSet.has(d));
    expect(missing, `demos not listed on the Demos page (run: node scripts/generate-demos-list.mjs):\n  ${missing.join('\n  ')}`).toEqual([]);
  });

  test('every listed link points at a real demo file (no stale)', () => {
    const stale = hrefs.filter((h) => !fs.existsSync(path.join(DEMOS_DIR, h)));
    expect(stale, `Demos page links to non-existent demo files:\n  ${[...new Set(stale)].join('\n  ')}`).toEqual([]);
  });

  test('demo links are root-relative (no ../ or leading /)', () => {
    expect(absolute, `Demos page links must be root-relative (they 404 under /wb-starter/):\n  ${absolute.join('\n  ')}`).toEqual([]);
  });
});
