import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

/**
 * COMPLIANCE GATE (#229): the Demos page lists EVERY demo in demos/.
 *
 * pages/demos.html is generated by scripts/generate-demos-list.mjs. This gate
 * fails if the page drifts from the folder — a demo added to demos/ but not
 * regenerated, a listed demo whose file was removed, or a link that isn't
 * root-relative (which 404s under the /wb-starter/ base). Regenerate with:
 *   node scripts/generate-demos-list.mjs
 */
const ROOT = process.cwd();
const DEMOS_DIR = path.join(ROOT, 'demos');
const PAGE = path.join(ROOT, 'pages', 'demos.html');

// Must match scripts/generate-demos-list.mjs — internal harnesses aren't listed.
const SKIP = /(^|[-.])(debug|test|test-harness|harness|check|scratch)([-.]|$)/i;

function expectedDemos(): string[] {
  return fs.readdirSync(DEMOS_DIR)
    // index.html (#237) is the directory's own plain listing page, not a demo —
    // it's excluded from this same generator's scan (scripts/generate-demos-list.mjs)
    // and doesn't belong on the SPA's separate pages/demos.html menu page either.
    .filter((n) => n.endsWith('.html') && n !== 'index.html' && !SKIP.test(n.replace(/\.html$/i, '')))
    .sort();
}

function listedDemos(): { hrefs: string[]; absolute: string[] } {
  const html = fs.readFileSync(PAGE, 'utf8');
  const hrefs: string[] = [];
  const absolute: string[] = [];
  for (const m of html.matchAll(/href="([^"]*demos\/[^"]+\.html)"/gi)) {
    const h = m[1];
    if (h.startsWith('/') || h.startsWith('../')) absolute.push(h);
    hrefs.push(h.replace(/^.*?demos\//, '')); // basename under demos/
  }
  return { hrefs, absolute };
}

test.describe('Demos page lists every demo (#229)', () => {
  const { hrefs, absolute } = listedDemos();
  const expected = expectedDemos();
  const listedSet = new Set(hrefs);

  test('lists every demos/*.html (no missing)', () => {
    const missing = expected.filter((d) => !listedSet.has(d));
    expect(missing, `demos not listed on the Demos page (run: node scripts/generate-demos-list.mjs):\n  ${missing.join('\n  ')}`).toEqual([]);
  });

  test('every listed link points at a real demo file (no stale)', () => {
    const stale = hrefs.filter((h) => !fs.existsSync(path.join(DEMOS_DIR, h)));
    expect(stale, `Demos page links to non-existent demo files:\n  ${[...new Set(stale)].join('\n  ')}`).toEqual([]);
  });

  test('demo links are root-relative (no ../ or leading /)', () => {
    expect(absolute, `Demos page links must be root-relative (they 404 under /wb-starter/):\n  ${absolute.join('\n  ')}`).toEqual([]);
  });
});

// Renamed from 'Demos menu is reachable from the shell nav (#229)': the menu no
// longer carries it (#1083), so the describe would have been claiming something
// untrue. The `site`/`nav` reads that fed the retired assertion are gone with
// it rather than left dangling.
test.describe('The demos page survives having no menu entry (#229, #1083)', () => {
  // #1083 — John: "remove the demos navigator item as well as the A.I. Docs".
  //
  // This required a navigationMenu entry with pageToLoad "demos", labelled
  // "Demos". Retired, not inverted, for the same reason as the A.I. Docs one:
  // this file's job is that the demos LIST is complete, and asserting the menu
  // must never carry the item would fight a future decision to restore it.
  //
  // The original note — "site-engine redirects unknown pages to home" — is why
  // the page-exists test further down matters MORE now, not less: a page that
  // stops existing does not 404, it silently renders HOME. Nothing links to
  // ?page=demos from the menu any more, so that test is the only thing left
  // standing between the page and a silent disappearance.

  test('the demos page still exists for anyone who visits it directly', () => {
    // Renamed from "the demos page the nav links to exists" — the nav no longer
    // links to it (#1083), but ?page=demos must still resolve.
    expect(fs.existsSync(PAGE), 'pages/demos.html (loaded by ?page=demos) must exist').toBe(true);
  });
});
