import { test, expect } from '../fixtures/offline';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

/**
 * #1530: demos/site/*.html said they were generated by scripts/generate-site.mjs
 * from src/wb-models/pages/x-component-library.site.json, but they had been
 * edited by hand through ordinary fix commits for weeks. Running the documented
 * command rewrote 9 of the 10 pages (836+/924-): it dropped the demo ids, put a
 * LOCAL /images/avatar.svg back over the remote avatars (#1187), renamed
 * sections, said "components" again, brought back x-views (#1101) and the
 * eager scan #987 had removed. So nobody could regenerate, and a generator fix
 * never reached the pages -- #1525 had to patch seven demos by hand.
 *
 * The hand edits now live in the site schema and the generator. This spec
 * regenerates into a temp directory (--out-dir, so the tracked files are never
 * touched) and requires every page, and the build report, to be exactly what
 * is committed -- the same contract #1452 put on the docs manifests.
 *
 * Fix a failure by changing the site schema or the generator and regenerating:
 *   node scripts/generate-site.mjs src/wb-models/pages/x-component-library.site.json
 *   node scripts/generate-demos-list.mjs
 * never by editing the HTML.
 */
const SITE_SCHEMA = 'src/wb-models/pages/x-component-library.site.json';
const PAGES_DIR = 'demos/site';
const REPORT = 'data/site-generator-result.json';

// Line endings are the checkout's business, not the generator's: a Windows
// checkout with autocrlf has CRLF on disk (#1452 failed on exactly this).
const read = (file: string) => fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');

/** "line N: committed <a> / generated <b>" for the first line that differs. */
function firstDifference(committed: string, generated: string): string {
  const a = committed.split('\n');
  const b = generated.split('\n');
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    if (a[i] !== b[i]) {
      return `line ${i + 1}:\n    committed: ${a[i] === undefined ? '(end of file)' : a[i].trim()}\n    generated: ${b[i] === undefined ? '(end of file)' : b[i].trim()}`;
    }
  }
  return '(identical)';
}

test('every demos/site page is exactly what generate-site.mjs produces (#1530)', () => {
  const out = fs.mkdtempSync(path.join(os.tmpdir(), 'wb-1530-'));
  try {
    execFileSync(process.execPath, ['scripts/generate-site.mjs', SITE_SCHEMA, '--out-dir', out], { encoding: 'utf8' });

    const generated = fs.readdirSync(out).filter((f) => f.endsWith('.html')).sort();
    expect(generated.length, 'the generator wrote pages').toBeGreaterThan(0);

    // Collect every page first, so one run names them all.
    const drifted: string[] = [];
    for (const file of generated) {
      const committedPath = path.join(PAGES_DIR, file);
      if (!fs.existsSync(committedPath)) {
        drifted.push(`${PAGES_DIR}/${file}: generated but not committed`);
        continue;
      }
      const committed = read(committedPath);
      const fresh = read(path.join(out, file));
      if (committed !== fresh) drifted.push(`${PAGES_DIR}/${file}: ${firstDifference(committed, fresh)}`);
    }
    expect(drifted, `committed pages differ from the generator's output:\n  ${drifted.join('\n  ')}\n`).toEqual([]);

    // The build report too, except where it was written: --out-dir moves it.
    const report = (file: string) => ({ ...JSON.parse(read(file)), outputDir: undefined });
    expect(report(path.join(out, 'site-generator-result.json')), `${REPORT} differs from the generator's report`)
      .toEqual(report(REPORT));
  } finally {
    fs.rmSync(out, { recursive: true, force: true });
  }
});

test('regenerating into a temp directory leaves the tracked files alone (#1530)', () => {
  const out = fs.mkdtempSync(path.join(os.tmpdir(), 'wb-1530-'));
  const tracked = [REPORT, ...fs.readdirSync(PAGES_DIR).map((f) => path.join(PAGES_DIR, f))];
  const before = tracked.map((f) => fs.readFileSync(f, 'utf8'));
  try {
    execFileSync(process.execPath, ['scripts/generate-site.mjs', SITE_SCHEMA, '--out-dir', out], { encoding: 'utf8' });
    tracked.forEach((f, i) => expect(fs.readFileSync(f, 'utf8'), `${f} was rewritten by an --out-dir run`).toBe(before[i]));
    // The generator used to drop a scratch copy of each page schema into
    // src/wb-models/pages/ while it ran.
    expect(fs.readdirSync('src/wb-models/pages').filter((f) => f.startsWith('_site-')), 'no scratch schemas left in src/').toEqual([]);
  } finally {
    fs.rmSync(out, { recursive: true, force: true });
  }
});
