/**
 * EVERY FILE IN ITS PLACE
 * =======================
 * The rules are written down in docs/standards/REPO-LAYOUT.md.
 *
 * John, 2026-09-29: "examine every file in wb-starter, follow our standards for
 * file name, folder placement etc. Move unused files by putting them into an
 * archive folder, no loose scripts, they all must go in proper folder. Same goes
 * with .png files. NO .txt files in root. Only 1 .html file in root."
 *
 * The audit that answered it found 20 stray root files (8 test-output .txt
 * dumps, a mistyped `--generate`, two loose scripts, a stray config, glow.png,
 * two extra .html pages) plus one-off scripts, temp data and screenshots. They
 * are in archive/ now, keeping their original paths. These checks keep the
 * layout from drifting back one convenient file at a time.
 *
 * Tracked files only (`git ls-files`): an untracked scratch file on someone's
 * machine is not the repo. archive/ and the create-wb-starter template copy
 * (regenerated by its sync script) are out of scope.
 */
import { test, expect } from '../fixtures/offline';
import { execFileSync } from 'child_process';
import path from 'path';
import { fileURLToPath } from 'url';
import { suiteEnv } from '../../scripts/lib/suite-env.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

// suiteEnv: never inherit the commit hook's GIT_DIR/GIT_INDEX_FILE (#1161).
const tracked = execFileSync('git', ['ls-files'], { cwd: ROOT, encoding: 'utf8', env: suiteEnv(process.env) })
  .split('\n').filter(Boolean)
  .filter((f) => !f.startsWith('archive/') && !f.startsWith('packages/create-wb-starter/template/'));
const rootFiles = tracked.filter((f) => !f.includes('/'));

test('the root holds exactly one .html file, index.html', () => {
  expect(rootFiles.filter((f) => f.endsWith('.html'))).toEqual(['index.html']);
});

test('README.md is the only .md file at the root', () => {
  // John: "no .md docs but readme in root". CLAUDE.md lives in .claude/ and
  // CONTRIBUTING.md in .github/ -- both locations their tools read.
  expect(rootFiles.filter((f) => f.toLowerCase().endsWith('.md'))).toEqual(['README.md']);
});

test('no .txt or .log file at the root', () => {
  expect(rootFiles.filter((f) => /\.(txt|log)$/i.test(f))).toEqual([]);
});

test('the root holds only the site entry points and project configuration', () => {
  // sw.js must stay at the root: a service worker's scope is its own folder
  // (CieloVistaStandards build-deploy.md, rule 2).
  const ALLOWED = new Set([
    '.gitignore', '.mcp.json', '.nojekyll', 'LICENSE', 'README.md',
    'eslint.config.js', 'global.d.ts', 'index.html', 'jsconfig.json', 'manifest.json',
    'package-lock.json', 'package.json', 'playwright.config.ts', 'server.js', 'sw.js', 'tsconfig.json',
  ]);
  expect(rootFiles.filter((f) => !ALLOWED.has(f)), 'move it to its folder, or archive/ if unused').toEqual([]);
});

test('scripts live in scripts/ (or with the code that runs them), never loose', () => {
  const SCRIPT = /\.(mjs|cjs|ps1|py|sh|bat|cmd)$/i;
  const HOMES = /^(scripts|src|tests|server|mcp-server|vscode|packages|\.husky|\.github|\.githooks|\.claude|\.devcontainer)\//;
  expect(tracked.filter((f) => SCRIPT.test(f) && !HOMES.test(f))).toEqual([]);
  // .js too, outside the folders whose .js is site or tool code.
  const JS_HOMES = /^(scripts|src|tests|server|mcp-server|vscode|packages|public|templates|\.husky|\.github)\//;
  expect(tracked.filter((f) => f.endsWith('.js') && f.includes('/') && !JS_HOMES.test(f))).toEqual([]);
});

test('images live in images/ or assets/ (fixtures, served pages and sample downloads excepted)', () => {
  const IMAGE = /\.(png|jpe?g|gif|webp|bmp|ico)$/i;
  // tests/fixtures: offline test media. files/: the sample downloads the
  // x-cardfile demos offer (a photo beside a PDF, a zip and a .doc).
  const HOMES = /^(images|assets|tests\/fixtures|public|src|vscode|\.github|files)\//;
  expect(tracked.filter((f) => IMAGE.test(f) && !HOMES.test(f))).toEqual([]);
});
