/**
 * AUTO-GENERATED by scripts/stamp-version.js — do not hand-edit.
 * Regenerated on every commit via .husky/pre-commit.
 */
export const VERSION = {
  "version": "3.0.2",
  "commit": "ad005b7",
  "builtAt": "2026-07-31T01:39:05.954Z"
};
