/**
 * AUTO-GENERATED by scripts/stamp-version.js — do not hand-edit.
 * Regenerated on every commit via .husky/pre-commit.
 */
export const VERSION = {
  "version": "3.0.42",
  "commit": "28fee16",
  "builtAt": "2026-08-20T18:46:52.080Z"
};
