/**
 * AUTO-GENERATED by scripts/stamp-version.js — do not hand-edit.
 * Regenerated on every commit via .husky/pre-commit.
 */
export const VERSION = {
  "version": "3.0.18",
  "commit": "e151cbd",
  "builtAt": "2026-08-18T00:20:40.971Z"
};
