/**
 * Regenerates src/core/version.js AND cache-busts every local <link>/<script>
 * reference in the HTML entry points, so a deploy is never at the mercy of
 * the CDN, a browser's disk cache, an old service worker, or a carrier's
 * transparent proxy — a changed query string is a URL nothing has cached
 * yet, so there is nothing to serve stale. Run automatically by the
 * pre-commit hook; never hand-edit src/core/version.js.
 */
import { execSync } from 'child_process';
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));

let commit = 'unknown';
try {
  commit = execSync('git rev-parse --short HEAD', { cwd: root, encoding: 'utf8' }).trim();
} catch {
  // no git available (e.g. fresh checkout without history) — leave 'unknown'
}

const builtAt = new Date().toISOString();

const out = `/**
 * AUTO-GENERATED by scripts/stamp-version.js — do not hand-edit.
 * Regenerated on every commit via .husky/pre-commit.
 */
export const VERSION = ${JSON.stringify({ version: pkg.version, commit, builtAt }, null, 2)};
`;

writeFileSync(path.join(root, 'src', 'core', 'version.js'), out);
console.log(`[stamp-version] v${pkg.version} (${commit}) @ ${builtAt}`);

// Cache-bust local resource references (src/… and config/…) in every HTML
// entry point. Leaves external URLs (fonts, CDNs) and already-anchored hash
// links alone — only same-origin src/config paths get a ?v= stamp.
const ENTRY_HTML = ['index.html', 'project-index.html'];
const ATTR_RE = /((?:href|src)=")((?:\.\/)?(?:src|config)\/[^"?]+)(?:\?[^"]*)?(")/g;

for (const file of ENTRY_HTML) {
  const filePath = path.join(root, file);
  let html;
  try {
    html = readFileSync(filePath, 'utf8');
  } catch {
    continue; // entry point doesn't exist in this checkout
  }
  // Cache-bust on the VERSION, not the commit hash. `git rev-parse HEAD` here
  // reads the PARENT commit — this runs before the commit being made exists —
  // so the token was always one commit behind the change it exists to bust.
  // A CSS-only release therefore shipped with an unchanged ?v= and never
  // reached any browser holding the old file (measured: 3.0.63 deployed with
  // ?v=80d6768, the 3.0.62 commit). pkg.version is known before the commit,
  // changes exactly when a release ships, and is what the release is named
  // after. See #743.
  const stamped = html.replace(ATTR_RE, (_match, pre, url, post) => `${pre}${url}?v=${pkg.version}${post}`);
  if (stamped !== html) {
    writeFileSync(filePath, stamped);
    console.log(`[stamp-version] cache-busted ${file}`);
  }
}
