/**
 * Regenerates src/core/version.js so the header's version badge always
 * reflects what's actually committed — package.json's version, the current
 * commit's short SHA, and a build timestamp. Run automatically by the
 * pre-commit hook; never hand-edit src/core/version.js.
 */
import { execSync } from 'child_process';
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));

let commit = 'unknown';
try {
  commit = execSync('git rev-parse --short HEAD', { cwd: root, encoding: 'utf8' }).trim();
} catch {
  // no git available (e.g. fresh checkout without history) — leave 'unknown'
}

const builtAt = new Date().toISOString();

const out = `/**
 * AUTO-GENERATED by scripts/stamp-version.js — do not hand-edit.
 * Regenerated on every commit via .husky/pre-commit.
 */
export const VERSION = ${JSON.stringify({ version: pkg.version, commit, builtAt }, null, 2)};
`;

writeFileSync(path.join(root, 'src', 'core', 'version.js'), out);
console.log(`[stamp-version] v${pkg.version} (${commit}) @ ${builtAt}`);
