import { test, expect } from '../fixtures/offline';

/**
 * #1736 -- a `target` demo must have somewhere to open.
 *
 * demos/site/forms.html (generated by scripts/generate-site.mjs from
 * button.schema.json) showed <button target="_self"> and <button target="_blank">
 * with no href. target only says WHERE an href opens, so both demos did nothing
 * and semantics/button.js warned for each: '[x-button] target="_self" has no
 * effect without an href'. The generator now gives every target demo an href
 * (its own section), through DEMO_COMPANIONS.
 *
 * See it by hand: open demos/site/forms.html with the devtools console open and
 * scroll to "target variants". Before: two "has no effect without an href"
 * warnings. Now: none, and each button links to the section.
 */

test('forms.html target demos carry an href and log no target warning', async ({ page }) => {
  const warnings: string[] = [];
  page.on('console', (m) => { if (/has no effect without an href/.test(m.text())) warnings.push(m.text()); });

  await page.goto('/demos/site/forms.html', { waitUntil: 'domcontentloaded' });
  const section = page.locator('#button-target-variants');
  await section.scrollIntoViewIfNeeded();
  const buttons = section.locator('button[target]');
  await expect(buttons).toHaveCount(2);
  // button.js adds .x-button in the same synchronous pass that checks target.
  for (let i = 0; i < 2; i++) await expect(buttons.nth(i)).toHaveClass(/\bx-button\b/, { timeout: 15000 });

  expect(warnings, 'a target demo with nowhere to open').toEqual([]);
  for (let i = 0; i < 2; i++) await expect(buttons.nth(i)).toHaveAttribute('href', '#button-target-variants');
});
