import { test, expect, Page } from '@playwright/test';

/**
 * button.css has NO bare `.wb-btn { ... }` base rule -- every rule in that file
 * for the `.wb-btn` family is a COMPOUND selector, `.wb-btn.wb-btn--{variant}`,
 * requiring BOTH the base class AND a modifier class together to produce any
 * visible styling. An element with ONLY `class="wb-btn"` (no `.wb-btn--*`
 * modifier) got ZERO styling -- no padding, no border, no background, nothing.
 * Confirmed live: `<wb-modal class="wb-btn" ...>` rendered as an invisible
 * element for exactly this reason.
 *
 * A repo-wide audit found bare `class="wb-btn"` (no modifier) in:
 *   - pages/behaviors.html: the Drawer demo's two `<wb-drawer class="wb-btn">`
 *     triggers, and the Modal demo's `<wb-modal class="wb-btn">` trigger
 *     (generated by scripts/generate-behaviors-page.js).
 *   - pages/components.html: 16 native `<button class="wb-btn">` triggers for
 *     Alerts/Modal/Drawer/Confirm/Prompt/Lightbox/Popover/Copy/Share/Print/
 *     Fullscreen/Dark-mode demos.
 *   - demos/landing-page-showcase.html: one `<button class="wb-btn" x-tooltip
 *     x-ripple>` demo button.
 *
 * None of these can be fixed by adding a `.wb-btn--{variant}` modifier CLASS
 * in these files: tests/compliance/no-wb-btn-class.spec.ts (#296) forbids
 * `class="wb-btn wb-btn--*"` long-hand in demos/pages/public/articles, in
 * favor of `variant="…"`/`size="…"` attributes. And a `variant` ATTRIBUTE
 * doesn't help either here: `<wb-modal>`/`<wb-drawer>` aren't `<button>` or
 * `<wb-button>` so button.js's variant-to-class wiring never touches them, and
 * every affected native `<button>` above is paired with an `x-*` behavior
 * (x-toast/x-drawer/x-confirm/x-prompt/x-lightbox/x-popover/x-copy/x-share/
 * x-print/x-fullscreen/x-darkmode/x-tooltip) which button.js's native-button
 * branch deliberately skips styling, by design, to avoid clobbering other
 * behaviors. CSS class matching is the only mechanism left, so the actual fix
 * is a defensive, purely-additive bare `.wb-btn` base rule in button.css
 * (specificity 0,1,0 -- strictly below every `.wb-btn.wb-btn--*` compound
 * rule's 0,2,0, so existing correctly-modified buttons keep their variant
 * colors on every property the compound rules set).
 *
 * This test asserts every bare (`.wb-btn` without a `.wb-btn--*` sibling
 * class) element on the affected pages now renders with a real, non-invisible
 * box -- a non-transparent background-color OR a real (non-`0px none`) border
 * -- the same diagnostic used elsewhere this session
 * (tests/regression/card-typed-variants-no-op.spec.ts,
 * tests/regression/behaviors-page-progress-bars.spec.ts) to catch a behavior
 * that "exists in the DOM" but renders with zero visible styling.
 */

const HARNESS = '/demos/test-harness.html';

async function inject(page: Page, html: string) {
  await page.goto(HARNESS);
  await page.waitForFunction(
    () => (window as any).WB && (window as any).WB.behaviors && Object.keys((window as any).WB.behaviors).length > 0,
    { timeout: 10000 }
  );
  await page.evaluate(async (h: string) => {
    const existing = document.getElementById('test-container');
    if (existing) existing.remove();
    const container = document.createElement('div');
    container.id = 'test-container';
    container.innerHTML = h;
    document.body.appendChild(container);
    await (window as any).WB.scan(container, { eager: true });
  }, html);
}

/** Real box-model presence: non-transparent background OR a real border. */
async function hasVisibleBoxStyle(page: Page, selector: string) {
  return page.locator(selector).first().evaluate((el) => {
    const cs = getComputedStyle(el as Element);
    const hasBg = cs.backgroundColor !== 'rgba(0, 0, 0, 0)' && cs.backgroundColor !== 'transparent';
    const hasBorder = cs.border !== '0px none' && !/^0px\b/.test(cs.borderWidth || '');
    return { hasBg, hasBorder, backgroundColor: cs.backgroundColor, border: cs.border };
  });
}

/** Every `.wb-btn` element on the page that does NOT also carry a
 * `.wb-btn--*` modifier class -- the exact shape of the bug. */
async function bareWbBtnCount(page: Page) {
  return page.evaluate(() => {
    return Array.from(document.querySelectorAll('.wb-btn')).filter(
      (el) => !Array.from(el.classList).some((c) => c.startsWith('wb-btn--'))
    ).length;
  });
}

test.describe('Bare .wb-btn (no modifier) renders with real visible styling', () => {
  test('via test-harness injection: bare wb-btn on a plain element and a native button', async ({ page }) => {
    // button.css is loaded just-in-time (src/styles/behavior-css-manifest.js)
    // the first time the 'button' behavior actually runs on the page -- a
    // bare `class="wb-btn"` element alone never triggers that (no variant
    // attribute, no <wb-button> tag). Every real occurrence of bare wb-btn
    // found in this audit lives on a page (behaviors.html, components.html)
    // that ALSO has genuine `<button variant="…">` elements elsewhere, which
    // is what actually loads button.css page-wide -- confirmed by the two
    // real-page tests below passing. Include one such trigger here too, so
    // this isolated harness case matches real page conditions instead of
    // testing an unlinked-stylesheet scenario the defensive rule was never
    // meant to solve on its own.
    await inject(page, `
      <button id="css-trigger" variant="primary">Trigger button.css load</button>
      <div id="bare-div" class="wb-btn">Bare div trigger</div>
      <button id="bare-button" class="wb-btn">Bare button trigger</button>
    `);

    const divStyle = await hasVisibleBoxStyle(page, '#bare-div');
    expect(divStyle.hasBg || divStyle.hasBorder, `bare div.wb-btn must be visibly styled, got ${JSON.stringify(divStyle)}`).toBe(true);

    const btnStyle = await hasVisibleBoxStyle(page, '#bare-button');
    expect(btnStyle.hasBg || btnStyle.hasBorder, `bare button.wb-btn must be visibly styled, got ${JSON.stringify(btnStyle)}`).toBe(true);
  });

  test('existing .wb-btn.wb-btn--primary keeps its variant background (no regression)', async ({ page }) => {
    await inject(page, `<button id="primary-btn" class="wb-btn wb-btn--primary">Primary</button>`);
    const style = await hasVisibleBoxStyle(page, '#primary-btn');
    // The variant background must still be the primary color, not the
    // defensive rule's neutral fallback.
    expect(style.hasBg, `wb-btn--primary must keep a real background, got ${JSON.stringify(style)}`).toBe(true);
  });

  test.describe('pages/behaviors.html', () => {
    test.beforeEach(async ({ page }) => {
      await page.goto('/?page=behaviors');
      await page.waitForFunction(() => (window as any).WB && (window as any).WB.behaviors, { timeout: 20000 });
      await page.waitForFunction(() => (window as any).WBSite && (window as any).WBSite.currentPage, { timeout: 20000 });
      await page.waitForTimeout(1000);
    });

    test('Modal trigger (wb-modal.wb-btn) is visibly styled', async ({ page }) => {
      const style = await hasVisibleBoxStyle(page, 'wb-modal.wb-btn');
      expect(style.hasBg || style.hasBorder, `Open Modal trigger must be visibly styled, got ${JSON.stringify(style)}`).toBe(true);
    });

    test('Drawer triggers (wb-drawer.wb-btn) are visibly styled', async ({ page }) => {
      const drawers = page.locator('wb-drawer.wb-btn');
      const count = await drawers.count();
      expect(count, 'expected 2 drawer triggers (Left/Right)').toBeGreaterThanOrEqual(2);
      for (let i = 0; i < count; i++) {
        const style = await drawers.nth(i).evaluate((el) => {
          const cs = getComputedStyle(el);
          return {
            hasBg: cs.backgroundColor !== 'rgba(0, 0, 0, 0)' && cs.backgroundColor !== 'transparent',
            hasBorder: cs.border !== '0px none',
          };
        });
        expect(style.hasBg || style.hasBorder, `drawer trigger #${i} must be visibly styled`).toBe(true);
      }
    });
  });

  test.describe('pages/components.html', () => {
    test.beforeEach(async ({ page }) => {
      await page.goto('/?page=components');
      await page.waitForFunction(() => (window as any).WB && (window as any).WB.behaviors, { timeout: 20000 });
      await page.waitForFunction(() => (window as any).WBSite && (window as any).WBSite.currentPage, { timeout: 20000 });
      await page.waitForTimeout(1000);
    });

    test('every bare .wb-btn trigger on the page is visibly styled', async ({ page }) => {
      const bareCount = await bareWbBtnCount(page);
      // The audit found 16 bare wb-btn triggers on this page (toast alerts,
      // modal, drawer, confirm, prompt, lightbox, popover, copy/share/print/
      // fullscreen, dark-mode). Guard that the page still HAS bare instances
      // to actually exercise -- if this drops to 0 the scenario no longer
      // applies and the test below would pass vacuously.
      expect(bareCount, 'expected bare (unmodified) .wb-btn triggers on components.html').toBeGreaterThan(0);

      const results = await page.evaluate(() => {
        const els = Array.from(document.querySelectorAll('.wb-btn')).filter(
          (el) => !Array.from(el.classList).some((c) => c.startsWith('wb-btn--'))
        );
        return els.map((el) => {
          const cs = getComputedStyle(el);
          const hasBg = cs.backgroundColor !== 'rgba(0, 0, 0, 0)' && cs.backgroundColor !== 'transparent';
          const hasBorder = cs.border !== '0px none';
          return {
            text: (el.textContent || '').trim().slice(0, 30),
            visible: hasBg || hasBorder,
          };
        });
      });

      const invisible = results.filter((r) => !r.visible);
      expect(invisible, `these bare .wb-btn triggers rendered with no background/border: ${JSON.stringify(invisible)}`).toEqual([]);
    });
  });

  test('demos/landing-page-showcase.html: bare wb-btn demo button is visibly styled', async ({ page }) => {
    await page.goto('/demos/landing-page-showcase.html');
    await page.waitForFunction(() => (window as any).WB && (window as any).WB.behaviors, { timeout: 20000 });
    await page.waitForTimeout(500);

    const style = await hasVisibleBoxStyle(page, 'button.wb-btn');
    expect(style.hasBg || style.hasBorder, `"Hover + click me" demo button must be visibly styled, got ${JSON.stringify(style)}`).toBe(true);
  });
});
