import { test, expect, Page } from '../fixtures/offline';

import { settlePage } from '../base';
/**
 * button.css has NO bare `.x-btn { ... }` base rule -- every rule in that file
 * for the `.x-btn` family is a COMPOUND selector, `.x-btn.x-btn--{variant}`,
 * requiring BOTH the base class AND a modifier class together to produce any
 * visible styling. An element with ONLY `class="x-btn"` (no `.x-btn--*`
 * modifier) got ZERO styling -- no padding, no border, no background, nothing.
 * Confirmed live: `<div x-modal class="x-btn" ...>` rendered as an invisible
 * element for exactly this reason.
 *
 * A repo-wide audit found bare `class="x-btn"` (no modifier) in:
 *   - pages/behaviors.html: the Drawer demo's two `<div x-drawer class="x-btn">`
 *     triggers, and the Modal demo's `<div x-modal class="x-btn">` trigger
 *     (generated by scripts/generate-behaviors-page.js).
 *   - pages/behaviors.html: 16 native `<button class="x-btn">` triggers for
 *     Alerts/Modal/Drawer/Confirm/Prompt/Lightbox/Popover/Copy/Share/Print/
 *     Fullscreen/Dark-mode demos.
 *   - demos/landing-page-showcase.html: one `<button class="x-btn" x-tooltip
 *     x-ripple>` demo button.
 *
 * None of these can be fixed by adding a `.x-btn--{variant}` modifier CLASS
 * in these files: tests/compliance/no-wb-btn-class.spec.ts (#296) forbids
 * `class="x-btn x-btn--*"` long-hand in demos/pages/public/articles, in
 * favor of `variant="…"`/`size="…"` attributes. And a `variant` ATTRIBUTE
 * doesn't help either here: `<div x-modal>`/`<div x-drawer>` aren't `<button>` or
 * `<button>` so button.js's variant-to-class wiring never touches them, and
 * every affected native `<button>` above is paired with an `x-*` behavior
 * (x-toast/x-drawer/x-confirm/x-prompt/x-lightbox/x-popover/x-copy/x-share/
 * x-print/x-fullscreen/x-darkmode/x-tooltip) which button.js's native-button
 * branch deliberately skips styling, by design, to avoid clobbering other
 * behaviors. CSS class matching is the only mechanism left, so the actual fix
 * is a defensive, purely-additive bare `.x-btn` base rule in button.css
 * (specificity 0,1,0 -- strictly below every `.x-btn.x-btn--*` compound
 * rule's 0,2,0, so existing correctly-modified buttons keep their variant
 * colors on every property the compound rules set).
 *
 * This test asserts every bare (`.x-btn` without a `.x-btn--*` sibling
 * class) element on the affected pages now renders with a real, non-invisible
 * box -- a non-transparent background-color OR a real (non-`0px none`) border
 * -- the same diagnostic used elsewhere this session
 * (tests/regression/card-typed-variants-no-op.spec.ts,
 * tests/regression/behaviors-page-progress-bars.spec.ts) to catch a behavior
 * that "exists in the DOM" but renders with zero visible styling.
 */

const HARNESS = '/demos/test-harness.html';

async function inject(page: Page, html: string) {
  await page.goto(HARNESS);
  await page.waitForFunction(
    () => (window as any).WB && (window as any).WB.behaviors && Object.keys((window as any).WB.behaviors).length > 0,
    { timeout: 10000 }
  );
  await page.evaluate(async (h: string) => {
    const existing = document.getElementById('test-container');
    if (existing) existing.remove();
    const container = document.createElement('div');
    container.id = 'test-container';
    container.innerHTML = h;
    document.body.appendChild(container);
    await (window as any).WB.scan(container, { eager: true });
  }, html);
}

/** Real box-model presence: non-transparent background OR a real border. */
async function hasVisibleBoxStyle(page: Page, selector: string) {
  return page.locator(selector).first().evaluate((el) => {
    const cs = getComputedStyle(el as Element);
    const hasBg = cs.backgroundColor !== 'rgba(0, 0, 0, 0)' && cs.backgroundColor !== 'transparent';
    const hasBorder = cs.border !== '0px none' && !/^0px\b/.test(cs.borderWidth || '');
    return { hasBg, hasBorder, backgroundColor: cs.backgroundColor, border: cs.border };
  });
}

/** Every `.x-btn` element on the page that does NOT also carry a
 * `.x-btn--*` modifier class -- the exact shape of the bug. */
async function bareWbBtnCount(page: Page) {
  return page.evaluate(() => {
    return Array.from(document.querySelectorAll('.x-btn')).filter(
      (el) => !Array.from(el.classList).some((c) => c.startsWith('x-btn--'))
    ).length;
  });
}

test.describe('Bare .x-btn (no modifier) renders with real visible styling', () => {
  test('via test-harness injection: bare x-btn on a plain element and a native button', async ({ page }) => {
    // button.css is loaded just-in-time (src/styles/behavior-css-manifest.js)
    // the first time the 'button' behavior actually runs on the page -- a
    // bare `class="x-btn"` element alone never triggers that (no variant
    // attribute, no <button> tag). Every real occurrence of bare x-btn
    // found in this audit lives on a page (behaviors.html, behaviors.html)
    // that ALSO has genuine `<button variant="…">` elements elsewhere, which
    // is what actually loads button.css page-wide -- confirmed by the two
    // real-page tests below passing. Include one such trigger here too, so
    // this isolated harness case matches real page conditions instead of
    // testing an unlinked-stylesheet scenario the defensive rule was never
    // meant to solve on its own.
    await inject(page, `
      <button id="css-trigger" variant="primary">Trigger button.css load</button>
      <div id="bare-div" class="x-btn">Bare div trigger</div>
      <button id="bare-button" class="x-btn">Bare button trigger</button>
    `);

    // button.css arrives when #css-trigger's behavior runs, which is after
    // inject() returns: reading the style once, at once, raced it and read an
    // unstyled box in CI. Wait for the stylesheet to apply; still a failure if
    // it never does.
    let divStyle: Awaited<ReturnType<typeof hasVisibleBoxStyle>> | undefined;
    await expect.poll(async () => {
      divStyle = await hasVisibleBoxStyle(page, '#bare-div');
      return divStyle.hasBg || divStyle.hasBorder;
    }, { message: `bare div.x-btn must be visibly styled, got ${JSON.stringify(divStyle)}` }).toBe(true);

    let btnStyle: Awaited<ReturnType<typeof hasVisibleBoxStyle>> | undefined;
    await expect.poll(async () => {
      btnStyle = await hasVisibleBoxStyle(page, '#bare-button');
      return btnStyle.hasBg || btnStyle.hasBorder;
    }, { message: `bare button.x-btn must be visibly styled, got ${JSON.stringify(btnStyle)}` }).toBe(true);
  });

  test('existing .x-btn.x-btn--primary keeps its variant background (no regression)', async ({ page }) => {
    await inject(page, `<button id="primary-btn" class="x-btn x-btn--primary">Primary</button>`);
    const style = await hasVisibleBoxStyle(page, '#primary-btn');
    // The variant background must still be the primary color, not the
    // defensive rule's neutral fallback.
    expect(style.hasBg, `x-btn--primary must keep a real background, got ${JSON.stringify(style)}`).toBe(true);
  });

  // These two ran against the Modal/Drawer demos pages/behaviors.html used to
  // carry. That page is now a catalogue that renders one example at a time
  // from data/behavior-examples.json (#666) and has no [x-modal].x-btn or
  // [x-drawer].x-btn at all -- so the modal test timed out and the drawer test
  // counted 0 triggers. The audited markup is injected instead, with a button
  // variant alongside it for the same reason as the harness test above (it is
  // what loads button.css on a real page).
  test.describe('audited behaviors.html triggers', () => {
    test.beforeEach(async ({ page }) => {
      await inject(page, `
        <button variant="primary">Trigger button.css load</button>
        <div x-modal class="x-btn" modal-title="Modal Dialog" modal-content="This is modal content.">Open Modal</div>
        <div x-drawer class="x-btn" title="Left Drawer" position="left">Left Drawer</div>
        <div x-drawer class="x-btn" title="Right Drawer" position="right">Right Drawer</div>
      `);
      // Lazy runtime (#491) + JIT CSS (#342): bring the triggers into view and
      // wait until each has been enhanced before reading computed styles.
      await page.locator('#test-container').scrollIntoViewIfNeeded();
      await page.waitForFunction(
        () => Array.from(document.querySelectorAll('#test-container [x-modal], #test-container [x-drawer]')).every((el) => el.hasAttribute('x-ready')),
        { timeout: 15000 }
      );
    });

    test('Modal trigger ([x-modal].x-btn) is visibly styled', async ({ page }) => {
      let style: Awaited<ReturnType<typeof hasVisibleBoxStyle>> | undefined;
      await expect.poll(async () => {
        style = await hasVisibleBoxStyle(page, '[x-modal].x-btn');
        return style.hasBg || style.hasBorder;
      }, { message: `Open Modal trigger must be visibly styled, got ${JSON.stringify(style)}` }).toBe(true);
    });

    test('Drawer triggers ([x-drawer].x-btn) are visibly styled', async ({ page }) => {
      const drawers = page.locator('[x-drawer].x-btn');
      const count = await drawers.count();
      expect(count, 'expected 2 drawer triggers (Left/Right)').toBeGreaterThanOrEqual(2);
      for (let i = 0; i < count; i++) {
        const style = await drawers.nth(i).evaluate((el) => {
          const cs = getComputedStyle(el);
          return {
            hasBg: cs.backgroundColor !== 'rgba(0, 0, 0, 0)' && cs.backgroundColor !== 'transparent',
            hasBorder: cs.border !== '0px none',
          };
        });
        expect(style.hasBg || style.hasBorder, `drawer trigger #${i} must be visibly styled`).toBe(true);
      }
    });
  });

  // This walked pages/behaviors.html, whose 16 audited bare triggers went
  // away with the page's rewrite into a render-on-demand catalogue (#666), so
  // its own vacuity guard failed. demos/landing-page-showcase.html is the one
  // audited page that still ships authored bare markup
  // (`<button class="x-btn" x-tooltip x-ripple>`), which is the case the
  // defensive rule exists for.
  test.describe('demos/landing-page-showcase.html', () => {
    test.beforeEach(async ({ page }) => {
      await page.goto('/demos/landing-page-showcase.html');
      await page.waitForFunction(() => (window as any).WB && (window as any).WB.behaviors, null, { timeout: 20000 });
      await page.locator('button.x-btn[x-tooltip]').first().scrollIntoViewIfNeeded();
      await expect(page.locator('button.x-btn[x-tooltip]').first()).toHaveAttribute('x-ready', '', { timeout: 15000 });
    });

    test('every bare .x-btn trigger on the page is visibly styled', async ({ page }) => {
      const bareCount = await bareWbBtnCount(page);
      // Guard that the page still HAS bare instances to actually exercise --
      // if this drops to 0 the scenario no longer applies and the check below
      // would pass vacuously.
      expect(bareCount, 'expected bare (unmodified) .x-btn triggers on landing-page-showcase.html').toBeGreaterThan(0);

      const results = await page.evaluate(() => {
        const els = Array.from(document.querySelectorAll('.x-btn')).filter(
          (el) => !Array.from(el.classList).some((c) => c.startsWith('x-btn--'))
        );
        return els.map((el) => {
          const cs = getComputedStyle(el);
          const hasBg = cs.backgroundColor !== 'rgba(0, 0, 0, 0)' && cs.backgroundColor !== 'transparent';
          const hasBorder = cs.border !== '0px none';
          return {
            text: (el.textContent || '').trim().slice(0, 30),
            visible: hasBg || hasBorder,
          };
        });
      });

      const invisible = results.filter((r) => !r.visible);
      expect(invisible, `these bare .x-btn triggers rendered with no background/border: ${JSON.stringify(invisible)}`).toEqual([]);
    });
  });

  test('demos/landing-page-showcase.html: bare x-btn demo button is visibly styled', async ({ page }) => {
    await page.goto('/demos/landing-page-showcase.html');
    await page.waitForFunction(() => (window as any).WB && (window as any).WB.behaviors, { timeout: 20000 });
    // The demo is styled once WB settles (#1516: not 500ms).
    await settlePage(page, { timeout: 15000 });

    const style = await hasVisibleBoxStyle(page, 'button.x-btn');
    expect(style.hasBg || style.hasBorder, `"Hover + click me" demo button must be visibly styled, got ${JSON.stringify(style)}`).toBe(true);
  });
});
