/**
 * Regenerates src/core/version.js AND cache-busts every local <link>/<script>
 * reference in the HTML entry points, so a deploy is never at the mercy of
 * the CDN, a browser's disk cache, an old service worker, or a carrier's
 * transparent proxy — a changed query string is a URL nothing has cached
 * yet, so there is nothing to serve stale. Run automatically by the
 * pre-commit hook; never hand-edit src/core/version.js.
 */
import { execSync } from 'child_process';
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));

let commit = 'unknown';
try {
  commit = execSync('git rev-parse --short HEAD', { cwd: root, encoding: 'utf8' }).trim();
} catch {
  // no git available (e.g. fresh checkout without history) — leave 'unknown'
}

const builtAt = new Date().toISOString();

const out = `/**
 * AUTO-GENERATED by scripts/stamp-version.js — do not hand-edit.
 * Regenerated on every commit via .husky/pre-commit.
 */
export const VERSION = ${JSON.stringify({ version: pkg.version, commit, builtAt }, null, 2)};
`;

writeFileSync(path.join(root, 'src', 'core', 'version.js'), out);
console.log(`[stamp-version] v${pkg.version} (${commit}) @ ${builtAt}`);

// Cache-bust local resource references (src/… and config/…) in every HTML
// entry point. Leaves external URLs (fonts, CDNs) and already-anchored hash
// links alone — only same-origin src/config paths get a ?v= stamp.
// #783: only these two were ever cache-busted, so every standalone page under
// demos/ was served from the browser cache indefinitely. Fix the playground,
// reload, see the old page -- repeatedly, which reads as "still broken" and is
// indistinguishable from a fix that did not work. Any HTML entry point that
// loads local assets needs the stamp, not just the two SPA shells.
const ENTRY_HTML = ['index.html', 'project-index.html', ...standaloneEntries()];

function standaloneEntries() {
  const out = [];
  for (const dir of ['demos', 'pages']) {
    let names;
    try { names = readdirSync(path.join(root, dir)); } catch { continue; }
    for (const name of names) {
      if (name.endsWith('.html')) out.push(`${dir}/${name}`);
    }
  }
  return out;
}
// #783: `(?:\.\/)?` matched "src/..." and "./src/..." but NOT "../src/...",
// which is how every page under demos/ and pages/ reaches the same files.
// Those pages were therefore never stamped, and a browser held their CSS and
// modules indefinitely -- a fix would ship and the page would look unchanged,
// repeatedly. Allow any number of leading "../".
const ATTR_RE = /((?:href|src)=")((?:\.\.?\/)*(?:src|config)\/[^"?]+)(?:\?[^"]*)?(")/g;

for (const file of ENTRY_HTML) {
  const filePath = path.join(root, file);
  let html;
  try {
    html = readFileSync(filePath, 'utf8');
  } catch {
    continue; // entry point doesn't exist in this checkout
  }
  // Cache-bust on the VERSION, not the commit hash. `git rev-parse HEAD` here
  // reads the PARENT commit — this runs before the commit being made exists —
  // so the token was always one commit behind the change it exists to bust.
  // A CSS-only release therefore shipped with an unchanged ?v= and never
  // reached any browser holding the old file (measured: 3.0.63 deployed with
  // ?v=80d6768, the 3.0.62 commit). pkg.version is known before the commit,
  // changes exactly when a release ships, and is what the release is named
  // after. See #743.
  const stamped = html.replace(ATTR_RE, (_match, pre, url, post) => `${pre}${url}?v=${pkg.version}${post}`);
  if (stamped !== html) {
    writeFileSync(filePath, stamped);
    console.log(`[stamp-version] cache-busted ${file}`);
  }
}
